version: 0.2

env:
  variables:
    EC2_USER: "ec2-user"
    EC2_HOST: "<YOUR-EC2-PUBLIC-IP>"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - apt install -y openssh-clients

  pre_build:
    commands:
      - echo "$EC2_KEY" > key.pem
      - chmod 400 key.pem

  build:
    commands:
      - echo "Build successful"

  post_build:
    commands:
      - scp -o StrictHostKeyChecking=no -i key.pem app.py requirements.txt $EC2_USER@$EC2_HOST:/home/ec2-user/
      - ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST "
          sudo yum install python3 -y &&
          pip3 install flask &&
          nohup sudo python3 /home/ec2-user/app.py > output.log 2>&1 &
        "

artifacts:
  files:
    - '*/'