version: 0.2

env:
  variables:
    EC2_USER: "ec2-user"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing SSH client"
      - apt-get update -y
      - apt-get install -y openssh-client

  pre_build:
    commands:
      - echo "Creating SSH key"
      - echo "$EC2_KEY" > key.pem
      - chmod 400 key.pem
      - ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST "echo SSH Connection Successful"

  build:
    commands:
      - echo "Deploying application to EC2"

      - scp -o StrictHostKeyChecking=no -i key.pem \
        app.py requirements.txt \
        $EC2_USER@$EC2_HOST:/home/ec2-user/

      - |
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
          sudo yum install -y python3
          pip3 install --upgrade pip
          pip3 install -r /home/ec2-user/requirements.txt
          sudo pkill -f app.py || true
          nohup sudo python3 /home/ec2-user/app.py > app.log 2>&1 &
        EOF

post_build:
  commands:
    - echo "Deployment completed 🚀"
