version: 0.2

env:
  variables:
    EC2_USER: ec2-user
    EC2_HOST: 3.144.223.151

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing SSH client"
      - apt-get update -y
      - apt-get install -y openssh-client

  pre_build:
    commands:
      - echo "Creating SSH key file"
      - echo -e "$SSH_KEY" > key.pem
      - chmod 400 key.pem
      - echo "SSH key file details:"
      - ls -l key.pem

  build:
    commands:
      - echo "Build phase successful"

  post_build:
    commands:
      - echo "Copying files to EC2"
      - scp -o StrictHostKeyChecking=no -i key.pem app.py requirements.txt $EC2_USER@$EC2_HOST:/home/ec2-user/

      - echo "Running application on EC2"
      - |
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST '
          sudo yum install -y python3 python3-pip || sudo apt-get install -y python3 python3-pip
          python3 -m pip install --upgrade pip
          pip3 install -r /home/ec2-user/requirements.txt
          pkill -f app.py || true
          nohup python3 /home/ec2-user/app.py > output.log 2>&1 &
        '

artifacts:
  files:
    - app.py
    - requirements.txt
