version: 0.2

env:
  variables:
    EC2_USER: "ec2-user"
    EC2_HOST: "13.59.225.71"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing SSH client...
      - apt-get update -y
      - apt-get install -y openssh-client

  pre_build:
    commands:

      # This command properly formats the key with newlines
      - echo "$EC2_KEY" | awk '{gsub(/RSA /,"RSA\n"); gsub(/-----END/,"\n-----END"); print}' > key.pem
      - chmod 400 key.pem

  build:
    commands:
      - echo "Build successful"

  post_build:
    commands:
      - echo "Copying files to EC2..."
      - scp -o StrictHostKeyChecking=no -i key.pem app.py requirements.txt $EC2_USER@$EC2_HOST:/home/ec2-user/
      - ssh -v -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST "echo Connected"

      - echo "Executing remote commands..."
      - |
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
          sudo yum install -y python3
          cd /home/ec2-user
          pip3 install -r requirements.txt
          pkill -f app.py || true
          nohup python3 app.py > output.log 2>&1 &
        EOF
