version: 0.2

env:
  variables:
    EC2_USER: "ec2-user"
    EC2_HOST: "13.59.225.71"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - apt-get update -y
      - apt-get install -y openssh-client

  pre_build:
    commands:
      - echo "Formatting key..."
      - echo "$EC2_KEY" | awk '{gsub(/RSA /,"RSA\n"); gsub(/-----END/,"\n-----END"); print}' > key.pem
      - chmod 400 key.pem
      - echo "Checking SSH key validity..."
      - ssh-keygen -lf key.pem || echo "Key format invalid"

  build:
    commands:
      - echo "Build successful"

  post_build:
    commands:
      - echo "Attempting SCP..."
      - scp -v -o StrictHostKeyChecking=no -i key.pem app.py requirements.txt $EC2_USER@$EC2_HOST:/home/ec2-user/