version: 0.2

env:
  variables:
    EC2_USER: "ec2-user"
    EC2_HOST: "13.59.225.71"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - yum install -y openssh-clients

  pre_build:
    commands:
      - echo "Creating SSH key..."
      - echo "$EC2_KEY" > key.pem
      - chmod 400 key.pem
      - echo "Validating key format..."
      - ssh-keygen -lf key.pem

  build:
    commands:
      - echo "Build successful"

  post_build:
    commands:
      - echo "Testing SSH connectivity..."
      - ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST "whoami"
      - echo "Copying files to EC2..."
      - scp -o StrictHostKeyChecking=no -i key.pem app.py requirements.txt $EC2_USER@$EC2_HOST:/home/ec2-user/
