post_build:
  commands:
    - echo "Testing network connectivity"
    - ping -c 3 54.151.56.14 || true
    - echo "Testing SSH connection"
    - ssh -vvv -o StrictHostKeyChecking=no -i key.pem ec2-user@54.151.56.14 "echo SSH SUCCESS"
