version: 0.2

env:
  variables:
    EC2_USER: "ec2-user"        # change to ubuntu if your EC2 is Ubuntu AMI
    EC2_HOST: "13.59.225.71"    # your EC2 public IP

phases:
  install:
    commands:
      - echo "Installing SSH client..."
      - apt-get update -y
      - apt-get install -y openssh-client

  pre_build:
    commands:
      - echo "Creating SSH private key..."
      - printf "%s" "$EC2_KEY" > key.pem
      - chmod 400 key.pem

      - echo "Validating SSH key format..."
      - ssh-keygen -lf key.pem

      - echo "Listing workspace files..."
      - ls -la

  build:
    commands:
      - echo "Build phase completed successfully"

  post_build:
    commands:
      - echo "Testing SSH connection to EC2..."
      - ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST "whoami"

      - echo "Copying files to EC2..."
      - scp -o StrictHostKeyChecking=no -i key.pem app.py requirements.txt \
        $EC2_USER@$EC2_HOST:/home/$EC2_USER/

      - echo "Deployment completed successfullys"
