version: 0.2

phases:
  install:
    commands:
      - echo "Updating packages and installing dependencies"
      - apt-get update -y
      - apt-get install -y openssh-client python3-pip zip unzip
      
  pre_build:
    commands:
      - echo "Setting up SSH key"
      - echo -e "$SSH_KEY" > key.pem
      - chmod 400 key.pem
      - echo "Testing SSH connection"
      - ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST "echo 'SSH works!'"
      
  build:
    commands:
      - echo "Build phase - files ready"
      - ls -la app.py requirements.txt
      
  post_build:
    commands:
      - echo "Deploying to EC2..."
      # Copy files
      - scp -o StrictHostKeyChecking=no -i key.pem app.py requirements.txt $EC2_USER@$EC2_HOST:/home/ec2-user/
      # SSH and restart app
      - |
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
          cd /home/ec2-user
          # Install Python dependencies
          pip3 install -r requirements.txt --break-system-packages
          # Kill existing app if running
          pkill -f "python3 app.py" || true
          # Start app in background
          nohup python3 app.py > app.log 2>&1 &
          # Show status
          echo "App deployed - check: ps aux | grep app.py"
          tail -5 app.log
        EOF
      - echo "Deployment complete!"

artifacts:
  files:
    - app.py
    - requirements.txt
    - key.pem
