version: 0.2

env:
  variables:
    EC2_USER: ec2-user
    EC2_HOST: 54.193.115.177

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - apt-get update -y
      - apt-get install -y openssh-client

  pre_build:
    commands:
      - echo "$SSH_KEY" > key.pem
      - chmod 400 key.pem

  build:
    commands:
      - echo Build successful

  post_build:
    commands:
      - scp -o StrictHostKeyChecking=no -i key.pem app.py requirements.txt ec2-user@54.193.115.177:/home/ec2-user/
      - ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@54.193.115.177 'sudo yum install -y python3 && pip3 install flask && nohup python3 /home/ec2-user/app.py > output.log 2>&1 &'

artifacts:
  files:
    - app.py
    - requirements.txt
