version: 0.2

env:
  variables:
    EC2_USER: "ec2-user"
    EC2_HOST: "<YOUR-EC2-PUBLIC-IP>"
    DEPLOY_PATH: "/var/www/html"

phases:

  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Install required tools"
      - yum install -y openssh-clients unzip

  pre_build:
    commands:
      - echo "Preparing SSH key"
      - echo "$EC2_KEY" > key.pem
      - chmod 400 key.pem
      - echo "Source downloaded from GitHub successfully"

  build:
    commands:
      - echo "Running build phase"
      - python app.py || echo "No Python file"
      - echo "Zipping website files"
      - zip -r deploy.zip .

  post_build:
    commands:
      - echo "Deploying to EC2"
      - scp -o StrictHostKeyChecking=no -i key.pem deploy.zip $EC2_USER@$EC2_HOST:/home/ec2-user/
      - ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST "unzip -o deploy.zip"
      - ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST "sudo mv index.html $DEPLOY_PATH/"
      - echo "Deployment Finished"

artifacts:
  files:
    - deploy.zip